//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables;
using CMS.CustomTables.Types.DancingGoatMvc;

[assembly: RegisterCustomTable(CompanyDataItem.CLASS_NAME, typeof(CompanyDataItem))]

namespace CMS.CustomTables.Types.DancingGoatMvc
{
	/// <summary>
	/// Represents a content item of type CompanyDataItem.
	/// </summary>
	public partial class CompanyDataItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "DancingGoatMvc.CompanyData";


		/// <summary>
		/// The instance of the class that provides extended API for working with CompanyDataItem fields.
		/// </summary>
		private readonly CompanyDataItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Country1.
		/// </summary>
		[DatabaseField]
		public string Country1ID
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Country1ID"), @"");
			}
			set
			{
				SetValue("Country1ID", value);
			}
		}


		/// <summary>
		/// Country1 Display Name.
		/// </summary>
		[DatabaseField]
		public string Country1DisplayName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Country1DisplayName"), @"");
			}
			set
			{
				SetValue("Country1DisplayName", value);
			}
		}


		/// <summary>
		/// Country1 Name.
		/// </summary>
		[DatabaseField]
		public string Country1Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Country1Name"), @"");
			}
			set
			{
				SetValue("Country1Name", value);
			}
		}


		/// <summary>
		/// Country1 GUID.
		/// </summary>
		[DatabaseField]
		public Guid Country1GUID
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("Country1GUID"), Guid.Empty);
			}
			set
			{
				SetValue("Country1GUID", value);
			}
		}


		/// <summary>
		/// Country1 Last Modified.
		/// </summary>
		[DatabaseField]
		public DateTime Country1LastModified
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("Country1LastModified"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("Country1LastModified", value);
			}
		}


		/// <summary>
		/// Country1TwoLetterCode.
		/// </summary>
		[DatabaseField]
		public string Country1TwoLetterCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Country1TwoLetterCode"), @"");
			}
			set
			{
				SetValue("Country1TwoLetterCode", value);
			}
		}


		/// <summary>
		/// Country1 Three Letter Code.
		/// </summary>
		[DatabaseField]
		public string Country1ThreeLetterCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Country1ThreeLetterCode"), @"");
			}
			set
			{
				SetValue("Country1ThreeLetterCode", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with CompanyDataItem fields.
		/// </summary>
		[RegisterProperty]
		public CompanyDataItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with CompanyDataItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CompanyDataItemFields : AbstractHierarchicalObject<CompanyDataItemFields>
		{
			/// <summary>
			/// The content item of type CompanyDataItem that is a target of the extended API.
			/// </summary>
			private readonly CompanyDataItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CompanyDataItemFields" /> class with the specified content item of type CompanyDataItem.
			/// </summary>
			/// <param name="instance">The content item of type CompanyDataItem that is a target of the extended API.</param>
			public CompanyDataItemFields(CompanyDataItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Country1.
			/// </summary>
			public string Country1ID
			{
				get
				{
					return mInstance.Country1ID;
				}
				set
				{
					mInstance.Country1ID = value;
				}
			}


			/// <summary>
			/// Country1 Display Name.
			/// </summary>
			public string Country1DisplayName
			{
				get
				{
					return mInstance.Country1DisplayName;
				}
				set
				{
					mInstance.Country1DisplayName = value;
				}
			}


			/// <summary>
			/// Country1 Name.
			/// </summary>
			public string Country1Name
			{
				get
				{
					return mInstance.Country1Name;
				}
				set
				{
					mInstance.Country1Name = value;
				}
			}


			/// <summary>
			/// Country1 GUID.
			/// </summary>
			public Guid Country1GUID
			{
				get
				{
					return mInstance.Country1GUID;
				}
				set
				{
					mInstance.Country1GUID = value;
				}
			}


			/// <summary>
			/// Country1 Last Modified.
			/// </summary>
			public DateTime Country1LastModified
			{
				get
				{
					return mInstance.Country1LastModified;
				}
				set
				{
					mInstance.Country1LastModified = value;
				}
			}


			/// <summary>
			/// Country1TwoLetterCode.
			/// </summary>
			public string Country1TwoLetterCode
			{
				get
				{
					return mInstance.Country1TwoLetterCode;
				}
				set
				{
					mInstance.Country1TwoLetterCode = value;
				}
			}


			/// <summary>
			/// Country1 Three Letter Code.
			/// </summary>
			public string Country1ThreeLetterCode
			{
				get
				{
					return mInstance.Country1ThreeLetterCode;
				}
				set
				{
					mInstance.Country1ThreeLetterCode = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CompanyDataItem" /> class.
		/// </summary>
		public CompanyDataItem() : base(CLASS_NAME)
		{
			mFields = new CompanyDataItemFields(this);
		}

		#endregion
	}
}