//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.DancingGoatMvc;

[assembly: RegisterDocumentType(ContactUs.CLASS_NAME, typeof(ContactUs))]

namespace CMS.DocumentEngine.Types.DancingGoatMvc
{
	/// <summary>
	/// Represents a content item of type ContactUs.
	/// </summary>
	public partial class ContactUs : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "DancingGoatMvc.ContactUs";


		/// <summary>
		/// The instance of the class that provides extended API for working with ContactUs fields.
		/// </summary>
		private readonly ContactUsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ContactUsID.
		/// </summary>
		[DatabaseIDField]
		public int ContactUsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ContactUsID"), 0);
			}
			set
			{
				SetValue("ContactUsID", value);
			}
		}


		/// <summary>
		/// Company name.
		/// </summary>
		[DatabaseField]
		public string ContactUsName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactUsName"), @"");
			}
			set
			{
				SetValue("ContactUsName", value);
			}
		}


		/// <summary>
		/// Street.
		/// </summary>
		[DatabaseField]
		public string ContactUsStreet
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactUsStreet"), @"");
			}
			set
			{
				SetValue("ContactUsStreet", value);
			}
		}


		/// <summary>
		/// City.
		/// </summary>
		[DatabaseField]
		public string ContactUsCity
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactUsCity"), @"");
			}
			set
			{
				SetValue("ContactUsCity", value);
			}
		}


		/// <summary>
		/// Country.
		/// </summary>
		[DatabaseField]
		public string ContactUsCountry
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactUsCountry"), @"INDIA");
			}
			set
			{
				SetValue("ContactUsCountry", value);
			}
		}


		/// <summary>
		/// Zip code.
		/// </summary>
		[DatabaseField]
		public string ContactUsZipCode
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactUsZipCode"), @"");
			}
			set
			{
				SetValue("ContactUsZipCode", value);
			}
		}


		/// <summary>
		/// Phone.
		/// </summary>
		[DatabaseField]
		public string ContactUsPhone
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactUsPhone"), @"");
			}
			set
			{
				SetValue("ContactUsPhone", value);
			}
		}


		/// <summary>
		/// Email.
		/// </summary>
		[DatabaseField]
		public string ContactUsEmail
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ContactUsEmail"), @"");
			}
			set
			{
				SetValue("ContactUsEmail", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ContactUs fields.
		/// </summary>
		[RegisterProperty]
		public ContactUsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ContactUs fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ContactUsFields : AbstractHierarchicalObject<ContactUsFields>
		{
			/// <summary>
			/// The content item of type ContactUs that is a target of the extended API.
			/// </summary>
			private readonly ContactUs mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ContactUsFields" /> class with the specified content item of type ContactUs.
			/// </summary>
			/// <param name="instance">The content item of type ContactUs that is a target of the extended API.</param>
			public ContactUsFields(ContactUs instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ContactUsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ContactUsID;
				}
				set
				{
					mInstance.ContactUsID = value;
				}
			}


			/// <summary>
			/// Company name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.ContactUsName;
				}
				set
				{
					mInstance.ContactUsName = value;
				}
			}


			/// <summary>
			/// Street.
			/// </summary>
			public string Street
			{
				get
				{
					return mInstance.ContactUsStreet;
				}
				set
				{
					mInstance.ContactUsStreet = value;
				}
			}


			/// <summary>
			/// City.
			/// </summary>
			public string City
			{
				get
				{
					return mInstance.ContactUsCity;
				}
				set
				{
					mInstance.ContactUsCity = value;
				}
			}


			/// <summary>
			/// Country.
			/// </summary>
			public string Country
			{
				get
				{
					return mInstance.ContactUsCountry;
				}
				set
				{
					mInstance.ContactUsCountry = value;
				}
			}


			/// <summary>
			/// Zip code.
			/// </summary>
			public string ZipCode
			{
				get
				{
					return mInstance.ContactUsZipCode;
				}
				set
				{
					mInstance.ContactUsZipCode = value;
				}
			}


			/// <summary>
			/// Phone.
			/// </summary>
			public string Phone
			{
				get
				{
					return mInstance.ContactUsPhone;
				}
				set
				{
					mInstance.ContactUsPhone = value;
				}
			}


			/// <summary>
			/// Email.
			/// </summary>
			public string Email
			{
				get
				{
					return mInstance.ContactUsEmail;
				}
				set
				{
					mInstance.ContactUsEmail = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ContactUs" /> class.
		/// </summary>
		public ContactUs() : base(CLASS_NAME)
		{
			mFields = new ContactUsFields(this);
		}

		#endregion
	}
}