//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.OnlineForms;
using CMS.OnlineForms.Types;

[assembly: RegisterBizForm(MvcContactUsItem.CLASS_NAME, typeof(MvcContactUsItem))]

namespace CMS.OnlineForms.Types
{
	/// <summary>
	/// Represents a content item of type MvcContactUsItem.
	/// </summary>
	public partial class MvcContactUsItem : BizFormItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BizForm.MvcContactUs";


		/// <summary>
		/// The instance of the class that provides extended API for working with MvcContactUsItem fields.
		/// </summary>
		private readonly MvcContactUsItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// First Name.
		/// </summary>
		[DatabaseField]
		public string UserFirstName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("UserFirstName"), @"");
			}
			set
			{
				SetValue("UserFirstName", value);
			}
		}


		/// <summary>
		/// Last Name.
		/// </summary>
		[DatabaseField]
		public string UserLastName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("UserLastName"), @"");
			}
			set
			{
				SetValue("UserLastName", value);
			}
		}


		/// <summary>
		/// Email.
		/// </summary>
		[DatabaseField]
		public string UserEmail
		{
			get
			{
				return ValidationHelper.GetString(GetValue("UserEmail"), @"");
			}
			set
			{
				SetValue("UserEmail", value);
			}
		}


		/// <summary>
		/// Massage.
		/// </summary>
		[DatabaseField]
		public string UserMessage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("UserMessage"), @"");
			}
			set
			{
				SetValue("UserMessage", value);
			}
		}


		/// <summary>
		/// reCAPTCHA.
		/// </summary>
		[DatabaseField]
		public string Recaptcha
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Recaptcha"), @"");
			}
			set
			{
				SetValue("Recaptcha", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with MvcContactUsItem fields.
		/// </summary>
		[RegisterProperty]
		public MvcContactUsItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with MvcContactUsItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class MvcContactUsItemFields : AbstractHierarchicalObject<MvcContactUsItemFields>
		{
			/// <summary>
			/// The content item of type MvcContactUsItem that is a target of the extended API.
			/// </summary>
			private readonly MvcContactUsItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="MvcContactUsItemFields" /> class with the specified content item of type MvcContactUsItem.
			/// </summary>
			/// <param name="instance">The content item of type MvcContactUsItem that is a target of the extended API.</param>
			public MvcContactUsItemFields(MvcContactUsItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// First Name.
			/// </summary>
			public string UserFirstName
			{
				get
				{
					return mInstance.UserFirstName;
				}
				set
				{
					mInstance.UserFirstName = value;
				}
			}


			/// <summary>
			/// Last Name.
			/// </summary>
			public string UserLastName
			{
				get
				{
					return mInstance.UserLastName;
				}
				set
				{
					mInstance.UserLastName = value;
				}
			}


			/// <summary>
			/// Email.
			/// </summary>
			public string UserEmail
			{
				get
				{
					return mInstance.UserEmail;
				}
				set
				{
					mInstance.UserEmail = value;
				}
			}


			/// <summary>
			/// Massage.
			/// </summary>
			public string UserMessage
			{
				get
				{
					return mInstance.UserMessage;
				}
				set
				{
					mInstance.UserMessage = value;
				}
			}


			/// <summary>
			/// reCAPTCHA.
			/// </summary>
			public string Recaptcha
			{
				get
				{
					return mInstance.Recaptcha;
				}
				set
				{
					mInstance.Recaptcha = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="MvcContactUsItem" /> class.
		/// </summary>
		public MvcContactUsItem() : base(CLASS_NAME)
		{
			mFields = new MvcContactUsItemFields(this);
		}

		#endregion
	}
}